import React, { useState, useRef } from 'react'
import { Text, TextInput, View, ImageBackground, StyleSheet } from 'react-native'
import TextButton from '../../components/global/ui/TextButton'
import PropTypes from 'prop-types'
import { showMessage } from "react-native-flash-message";
import AsyncStorage from '@react-native-community/async-storage'

const STORAGE_KEY = '@save_score'

const TypeWordPage = () => { 

  const list = ['ACCOUNT','ACCURATE','ACRES','ACROSS','ACTION','ACTIVE','ACTIVITY',
  'ACTUAL','ACTUALLY','ADDITION','ADDITIONAL','ADJECTIVE','ADULT','ADVENTURE',
  'ADVICE','AFFECT','AFRAID','AFTER','AFTERNOON','AGAIN','AGAINST','AGREE','AHEAD',
  'AIRPLANE','ALIKE','ALIVE','ALLOW','ALMOST','ALONE','ALONG','ALOUD','ALPHABET',
  'ALREADY','ALSO','ALTHOUGH','AMONG','AMOUNT','ANCIENT','ANGLE','ANGRY','ANIMAL',
  'ANNOUNCED','ANOTHER','ANSWER','ANTS','ANYBODY','ANYONE','ANYTHING','ANYWAY',
  'ANYWHERE','APART','APARTMENT','APPEARANCE','APPLE','APPLIED','APPROPRIATE','AREA',
  'ARMY','AROUND','ARRANGE','ARRANGEMENT','ARRIVE','ARROW','ART','ARTICLE','ASIDE',
  'ASK','ASLEEP','ATMOSPHERE','ATOM','ATOMIC','ATTACHED','ATTACK','ATTEMPT','ATTENTION',
  'AUDIENCE','AUTHOR','AUTOMOBILE','AVAILABLE','AVERAGE','AVOID','AWARE','AWAY','BABY',
  'BACK','BADLY','BALANCE','BALL','BALLOON','BAND','BANK','BARE','BARK','BARN','BASE',
  'BASEBALL','BASIC','BASIS','BASKET','BATTLE','BEAN','BEAR','BEAT','BEAUTIFUL',
  'BEAUTY','BECAME','BECAUSE','BECOME','BECOMING','BEEN','BEFORE','BEGAN','BEGINNING',
  'BEGUN','BEHAVIOR','BEHIND','BEING','BELIEVED','BELL','BELONG','BELOW','BELT','BEND',
  'BENEATH','BENT','BESIDE','BEST','BETTER','BETWEEN','BEYOND','BICYCLE','BIGGER',
  'BIGGEST','BILL','BIRDS','BIRTH','BIRTHDAY','BITE','BLACK','BLANK','BLANKET','BLEW',
  'BLIND','BLOCK','BLOOD','BLOW','BLUE','BOARD','BOAT','BODY','BONE','BOOK','BORDER',
  'BORN','BOTH','BOTTLE','BOTTOM','BOUND','BOWL','BRAIN','BRANCH','BRASS','BRAVE',
  'BREAD','BREAK','BREAKFAST','BREATH','BREATHE','BREATHING','BREEZE','BRICK','BRIDGE',
  'BRIEF','BRIGHT','BRING','BROAD','BROKE','BROKEN','BROTHER','BROUGHT','BROWN','BRUSH',
  'BUFFALO','BUILD','BUILDING','BUILT','BURIED','BURN','BURST','BUSH','BUSINESS','BUSY',
  'BUTTER','CABIN','CAGE','CAKE','CALL','CALM','CAME','CAMERA','CAMP','CANAL','CANNOT',
  'CAPITAL','CAPTAIN','CAPTURED','CARBON','CARD','CARE','CAREFUL','CAREFULLY','CARRIED',
  'CARRY','CASE','CAST','CASTLE','CATCH','CATTLE','CAUGHT','CAUSE','CAVE','CELL','CENT',
  'CENTER','CENTRAL','CENTURY','CERTAIN','CERTAINLY','CHAIN','CHAIR','CHAMBER','CHANCE',
  'CHANGE','CHANGING','CHAPTER','CHARACTER','CHARACTERISTIC','CHARGE','CHART','CHECK',
  'CHEESE','CHEMICAL','CHEST','CHICKEN','CHIEF','CHILD','CHILDREN','CHOICE','CHOOSE',
  'CHOSE','CHOSEN','CHURCH','CIRCLE','CIRCUS','CITIZEN','CITY','CLASS','CLASSROOM',
  'CLAWS','CLAY','CLEAN','CLEAR','CLEARLY','CLIMATE','CLIMB','CLOCK','CLOSE', 'CLOSET',
  'CLOSELY','CLOSER','CLOTH','CLOTHES','CLOTHING','CLOUD','CLUB','COACH','COAL','COAST',
  'COAT','CODEPEN','COFFEE','COLD','COLLECT','COLLEGE','COLONY','COLOR','COLUMN',
  'COMBINATION','COMBINE','COME','COMFORTABLE','COMING','COMMAND','COMMON','COMMUNITY',
  'COMPANY','COMPARE','COMPASS','COMPLETE','COMPLETELY','COMPLEX','COMPOSED',
  'COMPOSITION','COMPOUND','CONCERNED','CONDITION','CONGRESS','CONNECTED','CONSIDER',
  'CONSIST','CONSONANT','CONSTANTLY','CONSTRUCTION','CONTAIN','CONTINENT','CONTINUED',
  'CONTRAST','CONTROL','CONVERSATION','COOK','COOKIES','COOL','COPPER','COPY','CORN',
  'CORNER','CORRECT','CORRECTLY','COST','COTTON','COULD','COUNT','COUNTRY','COUPLE',
  'COURAGE','COURSE','COURT','COVER','COWBOY','CRACK','CREAM','CREATE','CREATURE',
  'CREW','CROP','CROSS','CROWD','CURIOUS','CURRENT','CURVE','CUSTOMS','CUTTING',
  'DAILY','DAMAGE','DANCE','DANGER','DANGEROUS','DARK','DARKNESS','DATE','DAUGHTER',
  'DAWN','DEAD','DEAL','DEAR','DEATH','DECIDE','DECLARED','DEEP','DEEPLY','DEER',
  'DEFINITION','DEGREE','DEPEND','DEPTH','DESCRIBE','DESERT','DESIGN','DESK','DETAIL',
  'DETERMINE','DEVELOP','DEVELOPMENT','DIAGRAM','DIAMETER','DIFFER','DIFFERENCE',
  'DIFFERENT','DIFFICULT','DIFFICULTY','DINNER','DIRECT','DIRECTION','DIRECTLY',
  'DIRT','DIRTY','DISAPPEAR','DISCOVER','DISCOVERY','DISCUSS','DISCUSSION','DISEASE',
  'DISH','DISTANCE','DISTANT','DIVIDE','DIVISION','DOCTOR','DOES','DOING','DOLL',
  'DOLLAR','DONE','DONKEY','DOOR','DOUBLE','DOUBT','DOWN','DOZEN','DRAW','DRAWN',
  'DREAM','DRESS','DREW','DRIED','DRINK','DRIVE','DRIVEN','DRIVER','DRIVING','DROP',
  'DROPPED','DROVE','DUCK','DULL','DURING','DUST','DUTY','EACH','EAGER','EARLIER',
  'EARLY','EARN','EARTH','EASIER','EASILY','EAST','EASY','EATEN','EDGE','EDUCATION',
  'EFFECT','EFFORT','EIGHT','EITHER','ELECTRIC','ELECTRICITY','ELEMENT','ELEPHANT',
  'ELEVEN','ELSE','EMPTY','ENEMY','ENERGY','ENGINE','ENGINEER','ENJOY','ENOUGH','ENTER',
  'ENTIRE','ENTIRELY','ENVIRONMENT','EQUAL','EQUALLY','EQUATOR','EQUIPMENT','ESCAPE',
  'ESPECIALLY','ESSENTIAL','ESTABLISH','EVEN','EVENING','EVENT','EVENTUALLY','EVER',
  'EVERY','EVERYBODY','EVERYONE','EVERYTHING','EVERYWHERE','EVIDENCE','EXACT','EXACTLY',
  'EXAMINE','EXAMPLE','EXCELLENT','EXCEPT','EXCHANGE','EXCITED','EXCITEMENT','EXCITING',
  'EXCLAIMED','EXERCISE','EXIST','EXPECT','EXPERIENCE','EXPERIMENT','EXPLAIN',
  'EXPLANATION','EXPLORE','EXPRESS','EXPRESSION','EXTRA','FACE','FACING','FACT','FACTOR',
  'FACTORY','FAILED','FAIR','FAIRLY','FALL','FALLEN','FAMILIAR','FAMILY','FAMOUS',
  'FARM','FARMER','FARTHER','FAST','FASTENED','FASTER','FATHER','FAVORITE','FEAR',
  'FEATHERS','FEATURE','FEED','FEEL','FEET','FELL','FELLOW','FELT','FENCE','FEWER',
  'FIELD','FIERCE','FIFTEEN','FIFTH','FIFTY','FIGHT','FIGHTING','FIGURE','FILL','FILM',
  'FINAL','FINALLY','FIND','FINE','FINEST','FINGER','FINISH','FIRE','FIREPLACE','FIRM',
  'FIRST','FISH','FIVE','FLAG','FLAME','FLAT','FLEW','FLIES','FLIGHT','FLOATING','FLOOR',
  'FLOW','FLOWER','FOLKS','FOLLOW','FOOD','FOOT','FOOTBALL','FORCE','FOREIGN','FOREST',
  'FORGET','FORGOT','FORGOTTEN','FORM','FORMER','FORT','FORTH','FORTY','FORWARD','FOUGHT',
  'FOUND','FOUR','FOURTH','FRAME','FREE','FREEDOM','FREQUENTLY','FRESH','FRIEND',
  'FRIENDLY','FRIGHTEN','FROG','FROM','FRONT','FROZEN','FRUIT','FUEL','FULL','FULLY',
  'FUNCTION','FUNNY','FURNITURE','FURTHER','FUTURE','GAIN','GAME','GARAGE','GARDEN',
  'GASOLINE','GATE','GATHER','GAVE','GENERAL','GENERALLY','GENTLE','GENTLY','GETTING',
  'GIANT','GIFT','GIRL','GIVE','GIVEN','GIVING','GLAD','GLASS','GLOBE','GOES','GOLD',
  'GOLDEN','GONE','GOOD','GOOSE','GOVERNMENT','GRABBED','GRADE','GRADUALLY','GRAIN',
  'GRANDFATHER','GRANDMOTHER','GRAPH','GRASS','GRAVITY','GRAY','GREAT','GREATER',
  'GREATEST','GREATLY','GREEN','GREW','GROUND','GROUP','GROW','GROWN','GROWTH','GUARD',
  'GUESS','GUIDE','GULF','HABIT','HAIR','HALF','HALFWAY','HALL','HAND','HANDLE',
  'HANDSOME','HANG','HAPPEN','HAPPENED','HAPPILY','HAPPY','HARBOR','HARD','HARDER',
  'HARDLY','HAVE','HAVING','HEADED','HEADING','HEALTH','HEARD','HEARING','HEART','HEAT',
  'HEAVY','HEIGHT','HELD','HELLO','HELP','HELPFUL','HERD','HERE','HERSELF','HIDDEN',
  'HIDE','HIGH','HIGHER','HIGHEST','HIGHWAY','HILL','HIMSELF','HISTORY','HOLD','HOLE',
  'HOLLOW','HOME','HONOR','HOPE','HORN','HORSE','HOSPITAL','HOUR','HOUSE','HOWEVER','HUGE',
  'HUMAN','HUNDRED','HUNG','HUNGRY','HUNT','HUNTER','HURRIED','HURRY','HURT','HUSBAND',
  'IDEA','IDENTITY','IMAGE','IMAGINE','IMMEDIATELY','IMPORTANCE','IMPORTANT','IMPOSSIBLE',
  'IMPROVE','INCH','INCLUDE','INCLUDING','INCOME','INCREASE','INDEED','INDEPENDENT',
  'INDICATE','INDIVIDUAL','INDUSTRIAL','INDUSTRY','INFLUENCE','INFORMATION','INSIDE',
  'INSTANCE','INSTANT','INSTEAD','INSTRUMENT','INTEREST','INTERIOR','INTO','INTRODUCED',
  'INVENTED','INVOLVED','IRON','ISLAND','ITSELF','JACK','JOIN','JOINED','JOURNEY','JUDGE',
  'JUMP','JUNGLE','JUST','KEEP','KEPT','KIDS','KILL','KIND','KITCHEN','KNEW','KNIFE',
  'KNOW','KNOWLEDGE','KNOWN','LABEL','LABOR','LACK','LADY','LAID','LAKE','LAMP','LAND',
  'LANGUAGE','LARGE','LARGER','LARGEST','LAST','LATE','LATER','LAUGH','LAYERS','LEAD',
  'LEADER','LEAF','LEARN','LEAST','LEATHER','LEAVE','LEAVING','LEFT','LENGTH','LESSON',
  'LETTER','LEVEL','LIBRARY','LIFE','LIFT','LIGHT','LIKE','LIKELY','LIMITED','LINE',
  'LION','LIPS','LIQUID','LIST','LISTEN','LITTLE','LIVE','LIVING','LOAD','LOCAL','LOCATE',
  'LOCATION','LONELY','LONG','LONGER','LOOK','LOOSE','LOSE','LOSS','LOST','LOUD','LOVE',
  'LOVELY','LOWER','LUCK','LUCKY','LUNCH','LUNGS','LYING','MACHINE','MACHINERY','MADE',
  'MAGIC','MAGNET','MAIL','MAIN','MAINLY','MAJOR','MAKE','MAKING','MANAGED','MANNER',
  'MANUFACTURING','MANY','MARK','MARKET','MARRIED','MASS','MASSAGE','MASTER','MATERIAL',
  'MATHEMATICS','MATTER','MAYBE','MEAL','MEAN','MEANS','MEANT','MEASURE','MEAT','MEDICINE',
  'MEET','MELTED','MEMBER','MEMORY','MENTAL','MERELY','METAL','METHOD','MICE','MIDDLE',
  'MIGHT','MIGHTY','MILE','MILITARY','MILK','MILL','MIND','MINE','MINERALS','MINUTE',
  'MIRROR','MISSING','MISSION','MISTAKE','MIXTURE','MODEL','MODERN','MOLECULAR','MOMENT',
  'MONEY','MONKEY','MONTH','MOOD','MOON','MORE','MORNING','MOST','MOSTLY','MOTHER',
  'MOTION','MOTOR','MOUNTAIN','MOUSE','MOUTH','MOVE','MOVEMENT','MOVIE','MOVING','MUSCLE',
  'MUSIC','MUSICAL','MUST','MYSELF','MYSTERIOUS','NAILS','NAME','NATION','NATIONAL',
  'NATIVE','NATURAL','NATURALLY','NATURE','NEAR','NEARBY','NEARER','NEAREST','NEARLY',
  'NECESSARY','NECK','NEEDED','NEEDLE','NEEDS','NEGATIVE','NEIGHBOR','NEIGHBORHOOD',
  'NERVOUS','NEST','NEVER','NEWS','NEWSPAPER','NEXT','NICE','NIGHT','NINE','NOBODY',
  'NODDED','NOISE','NONE','NOON','NORTH','NOSE','NOTE','NOTED','NOTHING','NOTICE','NOUN',
  'NUMBER','NUMERAL','NUTS','OBJECT','OBSERVE','OBTAIN','OCCASIONALLY','OCCUR','OCEAN',
  'OFFER','OFFICE','OFFICER','OFFICIAL','OLDER','OLDEST','ONCE','ONLY','ONTO','OPEN',
  'OPERATION','OPINION','OPPORTUNITY','OPPOSITE','ORANGE','ORBIT','ORDER','ORDINARY',
  'ORGANIZATION','ORGANIZED','ORIGIN','ORIGINAL','OTHER','OUGHT','OURSELVES','OUTER',
  'OUTLINE','OUTSIDE','OVER','OWNER','OXYGEN','PACK','PACKAGE','PAGE','PAID','PAIN',
  'PAINT','PAIR','PALACE','PALE','PAPER','PARAGRAPH','PARALLEL','PARENT','PARK','PART',
  'PARTICLES','PARTICULAR','PARTICULARLY','PARTLY','PARTS','PARTY','PASS','PASSAGE',
  'PAST','PATH','PATTERN','PEACE','PENCIL','PEOPLE','PERCENT','PERFECT','PERFECTLY',
  'PERHAPS','PERIOD','PERSON','PERSONAL','PHRASE','PHYSICAL','PIANO','PICK','PICTURE',
  'PICTURED','PIECE','PILE','PILOT','PINE','PINK','PIPE','PITCH','PLACE','PLAIN','PLAN',
  'PLANE','PLANET','PLANNED','PLANNING','PLANT','PLASTIC','PLATE','PLATES','PLAY',
  'PLEASANT','PLEASE','PLEASURE','PLENTY','PLURAL','PLUS','POCKET','POEM','POET',
  'POETRY','POINT','POLE','POLICE','POLICEMAN','POLITICAL','POND','PONY','POOL','POOR',
  'POPULAR','POPULATION','PORCH','PORT','POSITION','POSITIVE','POSSIBLE','POSSIBLY',
  'POST','POTATOES','POUND','POUR','POWDER','POWER','POWERFUL','PRACTICAL','PRACTICE',
  'PREPARE','PRESENT','PRESIDENT','PRESS','PRESSURE','PRETTY','PREVENT','PREVIOUS',
  'PRICE','PRIDE','PRIMITIVE','PRINCIPAL','PRINCIPLE','PRINTED','PRIVATE','PRIZE',
  'PROBABLY','PROBLEM','PROCESS','PRODUCE','PRODUCT','PRODUCTION','PROGRAM','PROGRESS',
  'PROMISED','PROPER','PROPERLY','PROPERTY','PROTECTION','PROUD','PROVE','PROVIDE',
  'PUBLIC','PULL','PUPIL','PURE','PURPLE','PURPOSE','PUSH','PUTTING','QUARTER','QUEEN',
  'QUESTION','QUICK','QUICKLY','QUIET','QUIETLY','QUITE','RABBIT','RACE','RADIO',
  'RAILROAD','RAIN','RAISE','RANCH','RANGE','RAPIDLY','RATE','RATHER','RAYS','REACH',
  'READ','READER','READY','REAL','REALIZE','REAR','REASON','RECALL','RECEIVE','RECENT',
  'RECENTLY','RECOGNIZE','RECORD','REFER','REFUSED','REGION','REGULAR','RELATED',
  'RELATIONSHIP','RELIGIOUS','REMAIN','REMARKABLE','REMEMBER','REMOVE','REPEAT',
  'REPLACE','REPLIED','REPORT','REPRESENT','REQUIRE','RESEARCH','RESPECT','REST',
  'RESULT','RETURN','REVIEW','RHYME','RHYTHM','RICE','RICH','RIDE','RIDING','RIGHT',
  'RING','RISE','RISING','RIVER','ROAD','ROAR','ROCK','ROCKET','ROCKY','ROLL','ROOF',
  'ROOM','ROOT','ROPE','ROSE','ROUGH','ROUND','ROUTE','RUBBED','RUBBER','RULE',
  'RULER','RUNNING','RUSH','SADDLE','SAFE','SAFETY','SAID','SAIL','SALE','SALMON',
  'SALT','SAME','SAND','SANG','SATELLITES','SATISFIED','SAVE','SAVED','SCALE','SCARED',
  'SCENE','SCHOOL','SCIENCE','SCIENTIFIC','SCIENTIST','SCORE','SCREEN','SEARCH',
  'SEASON','SEAT','SECOND','SECRET','SECTION','SEED','SEEING','SEEMS','SEEN','SELDOM',
  'SELECT','SELECTION','SELL','SEND','SENSE','SENT','SENTENCE','SEPARATE','SERIES',
  'SERIOUS','SERVE','SERVICE','SETS','SETTING','SETTLE','SETTLERS','SEVEN','SEVERAL',
  'SHADE','SHADOW','SHAKE','SHAKING','SHALL','SHALLOW','SHAPE','SHARE','SHARP','SHEEP',
  'SHEET','SHELF','SHELLS','SHELTER','SHINE','SHINNING','SHIP','SHIRT','SHOE','SHOOT',
  'SHOP','SHORE','SHORT','SHORTER','SHOT','SHOULD','SHOULDER','SHOUT','SHOW','SHOWN',
  'SHUT','SICK','SIDES','SIGHT','SIGN','SIGNAL','SILENCE','SILENT','SILK','SILLY',
  'SILVER','SIMILAR','SIMPLE','SIMPLEST','SIMPLY','SINCE','SING','SINGLE','SINK',
  'SISTER','SITTING','SITUATION','SIZE','SKILL','SKIN','SLABS','SLAVE','SLEEP',
  'SLEPT','SLIDE','SLIGHT','SLIGHTLY','SLIP','SLIPPED','SLOPE','SLOW','SLOWLY','SMALL',
  'SMALLER','SMALLEST','SMELL','SMILE','SMOKE','SMOOTH','SNAKE','SNOW','SOAP','SOCIAL',
  'SOCIETY','SOFT','SOFTLY','SOIL','SOLAR','SOLD','SOLDIER','SOLID','SOLUTION',
  'SOLVE','SOME','SOMEBODY','SOMEHOW','SOMEONE','SOMETHING','SOMETIME','SOMEWHERE',
  'SONG','SOON','SORT','SOUND','SOURCE','SOUTH','SOUTHERN','SPACE','SPEAK','SPECIAL',
  'SPECIES','SPECIFIC','SPEECH','SPEED','SPELL','SPEND','SPENT','SPIDER','SPIN',
  'SPIRIT','SPITE','SPLIT','SPOKEN','SPORT','SPREAD','SPRING','SQUARE','STAGE',
  'STAIRS','STAND','STANDARD','STAR','STARED','START','STATE','STATEMENT','STATION',
  'STAY','STEADY','STEAM','STEEL','STEEP','STEMS','STEP','STEPPED','STICK','STIFF',
  'STILL','STOCK','STOMACH','STONE','STOOD','STOP','STOPPED','STORE','STORM','STORY',
  'STOVE','STRAIGHT','STRANGE','STRANGER','STRAW','STREAM','STREET','STRENGTH',
  'STRETCH','STRIKE','STRING','STRIP','STRONG','STRONGER','STRUCK','STRUCTURE',
  'STRUGGLE','STUCK','STUDENT','STUDIED','STUDYING','SUBJECT','SUBSTANCE','SUCCESS',
  'SUCCESSFUL','SUCH','SUDDEN','SUDDENLY','SUGAR','SUGGEST','SUIT','SUMMER','SUNLIGHT',
  'SUPPER','SUPPLY','SUPPORT','SUPPOSE','SURE','SURFACE','SURPRISE','SURROUNDED',
  'SWAM','SWEET','SWEPT','SWIM','SWIMMING','SWING','SWUNG','SYLLABLE','SYMBOL',
  'SYSTEM','TABLE','TAIL','TAKE','TAKEN','TALES','TALK','TALL','TANK','TAPE','TASK',
  'TASTE','TAUGHT','TEACH','TEACHER','TEAM','TEARS','TEETH','TELEPHONE','TELEVISION',
  'TELL','TEMPERATURE','TENT','TERM','TERRIBLE','TEST','THAN','THANK','THAT','THEE',
  'THEM','THEMSELVES','THEN','THEORY','THERE','THEREFORE','THESE','THEY','THICK',
  'THIN','THING','THINK','THIRD','THIRTY','THIS','THOSE','THOU','THOUGH','THOUGHT',
  'THOUSAND','THREAD','THREE','THREW','THROAT','THROUGH','THROUGHOUT','THROW',
  'THROWN','THUMB','THUS','TIDE','TIGHT','TIGHTLY','TILL','TIME','TINY','TIRED',
  'TITLE','TOBACCO','TODAY','TOGETHER','TOLD','TOMORROW','TONE','TONGUE','TONIGHT',
  'TOOK','TOOL','TOPIC','TORN','TOTAL','TOUCH','TOWARD','TOWER','TOWN','TRACE',
  'TRACK','TRADE','TRAFFIC','TRAIL','TRAIN','TRANSPORTATION','TRAP','TRAVEL','TREATED',
  'TREE','TRIANGLE','TRIBE','TRICK','TRIED','TRIP','TROOPS','TROPICAL','TROUBLE',
  'TRUCK','TRUNK','TRUTH','TUBE','TUNE','TURN','TWELVE','TWENTY','TWICE','TYPE',
  'TYPICAL','UNCLE','UNDER','UNDERLINE','UNDERSTANDING','UNHAPPY','UNION','UNIT',
  'UNIVERSE','UNKNOWN','UNLESS','UNTIL','UNUSUAL','UPON','UPPER','UPWARD','USEFUL',
  'USING','USUAL','USUALLY','VALLEY','VALUABLE','VALUE','VAPOR','VARIETY','VARIOUS',
  'VAST','VEGETABLE','VERB','VERTICAL','VERY','VESSELS','VICTORY','VIEW','VILLAGE',
  'VISIT','VISITOR','VOICE','VOLUME','VOTE','VOWEL','VOYAGE','WAGON','WAIT','WALK',
  'WALL','WANT','WARM','WARN','WASH','WASTE','WATCH','WATER','WAVE','WEAK','WEALTH',
  'WEAR','WEATHER','WEEK','WEIGH','WEIGHT','WELCOME','WELL','WENT','WERE','WEST',
  'WESTERN','WHALE','WHAT','WHATEVER','WHEAT','WHEEL','WHEN','WHENEVER','WHERE',
  'WHEREVER','WHETHER','WHICH','WHILE','WHISPERED','WHISTLE','WHITE',,'WHOLE','WHOM',
  'WHOSE','WIDE','WIDELY','WIFE','WILD','WILL','WILLING','WIND','WINDOW','WING','WINTER',
  'WIRE','WISE','WISH','WITH','WITHIN','WITHOUT','WOLF','WOMEN','WONDER','WONDERFUL',
  'WOOD','WOODEN','WOOL','WORD','WORE','WORK','WORKER','WORLD','WORRIED','WORRY',
  'WORSE','WORTH','WOULD','WRAPPED','WRITE','WRITER','WRITING','WRITTEN','WRONG','WROTE',
  'YARD','YEAR','YELLOW','YESTERDAY','YOUNG','YOUNGER','YOUR','YOURSELF','YOUTH','ZERO']

  const counter = useRef(15)
  const [score, setScore] = useState(0);
  const [timer, setTimer] = useState(15);
  const [targetWord, setTargetWord] = useState("");
  const [inputWord, setInputWord] = useState("");
  const [bestScore, setBestScore] = useState("");
   
  const saveData = async () => {
    const value = score
      try {
        await AsyncStorage.setItem(STORAGE_KEY, `${value}`)
      } catch (e) {
      }
    }

    const readData = async () => {
      try {
        const userScore = await AsyncStorage.getItem(STORAGE_KEY)
    
        if (userScore > bestScore) {
          setBestScore(parseInt(userScore))
        }
      } catch (e) {
      }
    }

    const startTimer = () => {
      counter.current = setInterval(() => {
        setTimer(timer => timer - 1);
      }, 1000);
    }

    const stopTimer = () => {
      clearInterval(counter.current)
      saveData()
      readData()
    }

    const newWord = () => {
          let randomWord = list[Math.floor(Math.random()*list.length)];
          setTargetWord(randomWord)
    }

    const newGame = () => {
        startTimer()
        newWord()
    }

    const restartGame = () => {
      setTimer(10)
      setScore(0)
      setInputWord('')
      newGame()
    }

    const onChange = (text) => {
      //tried using text instead of event
        setInputWord(text)
      }

    const handleOnSubmitEditing = (text) => {
      if (text.nativeEvent.text.toUpperCase() !== targetWord) {
        showMessage({
          position: 'center',
          textStyle: {marginTop: 20},
          message: "Try Again!",
          backgroundColor: "hotpink",
          color: "black",
          autoHide: true,
          duration: 500
        })
      } else {
          setScore(score + 1)
          setInputWord("")
          newWord()
        }
    }

    if(timer <= 0) stopTimer()

    return (
        <>
          {!targetWord ? 
            <View>
                <Text style={styles.rule}>Text as many words as you can before time runs out.</Text>
                <TextButton
                  title="Start New Game"
                  type="primary"
                  onPress={newGame}
                />
            </View>
          :
          <>
          {(timer <= 0) ?
            <View>
              <Text style={styles.text1}>Game Over!!!</Text>
              <Text style={styles.text3}>Your Score: {score}</Text>
              <Text style={styles.text4}>High Score: {bestScore}</Text>
              <TextButton
              style={styles.button}
              title="Replay?"
              type="primary"
              onPress={restartGame}
              />
            </View>
            :
            <View>
              <Text style={styles.text1}>SCORE: {score}</Text>
              <Text style={styles.text2}>TIME LEFT: {timer}</Text>
              <Text style={styles.word}>{targetWord}</Text>
              <TextInput 
                blurOnSubmit={false}
                enablesReturnKeyAutomatically={true}
                style={styles.textbox}
                type="text" 
                onChangeText={onChange}
                onSubmitEditing={text => handleOnSubmitEditing(text)}
                autoFocus={true}
                value={inputWord}/>
            </View>
            }
            </>
          }
            <ImageBackground style={styles.imageBackground}>
            </ImageBackground>
        </>
    )
}
const diameter = 300
const styles = StyleSheet.create({
    rule: {
      marginBottom: 40,
      fontSize: 30,
      textAlign: 'center',
      padding: 10,
      color: 'hotpink',
      paddingBottom: 110,
      paddingTop: 350
    },
    word: {
      paddingTop: 100, 
      fontSize: 50, 
      maxWidth: 350,
      textAlign: 'center'
    },
    text1: {
      textAlign: 'center', 
      fontSize: 30, 
      color: 'hotpink',
      padding: 10,
      paddingTop: 240,
    },
    text2: {
      textAlign: 'center', 
      fontSize: 30, 
      color: 'hotpink',
    },
    text3: {
      textAlign: 'center', 
      fontSize: 30, 
      color: 'hotpink',
      marginBottom: 200,
    },
    text4: {
      textAlign: 'center', 
      fontSize: 30, 
      color: 'hotpink',
      borderColor: 'pink',
      borderStyle: 'solid',
      borderWidth: 4,
      borderRadius: 10,
      marginBottom: 20
    },
    textbox:{
      backgroundColor: 'white',
      textAlign: 'center',
    },
    imageBackground: {
        width: diameter,
        height: diameter,
        resizeMode: 'cover',
        justifyContent: 'center',
    },
})

TypeWordPage.propTypes = {
  navigation: PropTypes.object.isRequired,
}

export default TypeWordPage